# Tensors in Pytorch
***



In [1]:
import torch


## Creation
```
x = torch.randn(*size)              # tensor with independent N(0,1) entries
x = torch.[ones|zeros](*size)       # tensor with all 1's [or 0's]
x = torch.tensor(L)                 # create tensor from [nested] list or ndarray L
y = x.clone()                       # clone of x
with torch.no_grad():               # code wrap that stops autograd from tracking tensor history
requires_grad=True                  # arg, when set to True, tracks computation
                                    # history for future derivative calculations
```

In [14]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.zeros((3,3), dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [22]:
torch.ones((3,3), dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [25]:
torch.empty((3,3), dtype=torch.int32)

tensor([[         0,          0, 1953702523],
        [1702130273,  540680804,  842019362],
        [ 909126965, 1412509997,  842674224]], dtype=torch.int32)

In [29]:
torch.rand((3,3), dtype=torch.float32)

tensor([[0.5117, 0.0197, 0.3306],
        [0.6186, 0.3496, 0.4891],
        [0.9648, 0.6378, 0.5571]])

In [37]:
# manual seed 
torch.manual_seed(100)
torch.rand((3,3))

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080]])

In [43]:
torch.arange(1,50, 5).reshape(2,5)

tensor([[ 1,  6, 11, 16, 21],
        [26, 31, 36, 41, 46]])

In [52]:
torch.linspace(1,20,20, dtype=torch.int32).reshape(2,10)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]], dtype=torch.int32)

In [54]:
torch.eye(3, dtype=torch.int32)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)

In [55]:
torch.empty_like(x)

tensor([[          762275552, 4607182418800017408, 4607182418800017408],
        [                 97,           761983776,           763054672]])

In [56]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [57]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [59]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])

***
## Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


***
## Dimensionality
```
x.size()                                  # return tuple-like object of dimensions
x = torch.cat(tensor_seq, dim=0)          # concatenates tensors along dim
y = x.view(a,b,...)                       # reshapes x into size (a,b,...)
y = x.view(-1,a)                          # reshapes x into size (b,a) for some b
y = x.transpose(a,b)                      # swaps dimensions a and b
y = x.permute(*dims)                      # permutes dimensions
y = x.unsqueeze(dim)                      # tensor with added axis
y = x.unsqueeze(dim=2)                    # (a,b,c) tensor -> (a,b,1,c) tensor
y = x.squeeze()                           # removes all dimensions of size 1 (a,1,b,1) -> (a,b)
y = x.squeeze(dim=1)                      # removes specified dimension of size 1 (a,1,b,1) -> (a,b,1)
```

In [89]:
y = torch.ones_like(x)
z = torch.cat([x,y], dim=0)
z.view(3, 4)

tensor([[1, 2, 3, 4],
        [5, 6, 1, 1],
        [1, 1, 1, 1]])

In [98]:
z.permute(dims=(-2,1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1],
        [1, 1, 1]])

In [109]:
print(
    x,
    x+2,
    x-2,
    x*2,
    x/2,
    x//2,
    (x//2)%2,
    sep='\n\n'
)

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[3, 4, 5],
        [6, 7, 8]])

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

tensor([[0, 1, 1],
        [2, 2, 3]])

tensor([[0, 1, 1],
        [0, 0, 1]])



## Algebra
```
ret = A.mm(B)       # matrix multiplication
ret = A.mv(x)       # matrix-vector multiplication
x = x.t()           # matrix transpose
```

In [112]:
x.mm(z.t())

tensor([[14, 32,  6,  6],
        [32, 77, 15, 15]])

In [123]:
z.mv(x[0])

tensor([14, 32,  6,  6])


## GPU usage
```
torch.cuda.is_available                                     # check for cuda
x = x.cuda()                                                # move x's data from
                                                            # CPU to GPU and return new object

x = x.cpu()                                                 # move x's data from GPU to CPU
                                                            # and return new object

if not args.disable_cuda and torch.cuda.is_available():     # device agnostic code
    args.device = torch.device('cuda')                      # and modularity
else:                                                       #
    args.device = torch.device('cpu')                       #

net.to(device)                                              # recursively convert their
                                                            # parameters and buffers to
                                                            # device specific tensors

x = x.to(device)                                            # copy your tensors to a device
                                                            # (gpu, cpu)
```

## Other functions
***

In [124]:
torch.round(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [126]:
torch.ceil(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [127]:
torch.floor(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [130]:
torch.abs(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [131]:
torch.neg(x)

tensor([[-1, -2, -3],
        [-4, -5, -6]])

In [135]:
torch.clamp(x, min=1, max=5)

tensor([[1, 2, 3],
        [4, 5, 5]])

In [138]:
torch.randint(size=(3,3), low=10, high=100, dtype=torch.float32)

tensor([[74., 51., 10.],
        [94., 63., 38.],
        [87., 34., 46.]])

In [148]:
print(
    x,
    torch.sum(x),
    torch.sum(x, dim=0),
    torch.sum(x, dim=1),
    # torch.mean(x, dim=1),
    torch.median(x),
    torch.max(x),
    torch.min(x),
    # torch.std(x),
    # torch.var(x),
    torch.argmax(x),
    torch.argmin(x),
    
    sep = "\n\n"
)

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor(21)

tensor([5, 7, 9])

tensor([ 6, 15])

tensor(3)

tensor(6)

tensor(1)

tensor(5)

tensor(0)


In [151]:
torch.matmul(x, z.T)

tensor([[14, 32,  6,  6],
        [32, 77, 15, 15]])

In [153]:
v1, v2 = x[0], x[-1]
torch.dot(v1, v2)

tensor(32)

In [154]:
torch.transpose(x, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [172]:
torch.manual_seed(100)
a = torch.randint(size=(3,3), low=10, high=100, dtype=torch.float32)
torch.det(a)


tensor(-52290.0156)

In [173]:
torch.inverse(a)

tensor([[-0.0578,  0.0716, -0.0282],
        [ 0.0960, -0.0899,  0.0234],
        [-0.0073, -0.0035,  0.0179]])

In [175]:
x > 3

tensor([[False, False, False],
        [ True,  True,  True]])

In [176]:
torch.log(v1)

tensor([0.0000, 0.6931, 1.0986])

In [177]:
torch.exp(v1)

tensor([ 2.7183,  7.3891, 20.0855])

In [178]:
torch.sqrt(v1)

tensor([1.0000, 1.4142, 1.7321])

In [179]:
torch.sigmoid(z)

tensor([[0.7311, 0.8808, 0.9526],
        [0.9820, 0.9933, 0.9975],
        [0.7311, 0.7311, 0.7311],
        [0.7311, 0.7311, 0.7311]])

In [184]:
torch.softmax(z.float(), dim=0)

tensor([[0.0433, 0.0458, 0.0468],
        [0.8700, 0.9205, 0.9405],
        [0.0433, 0.0169, 0.0063],
        [0.0433, 0.0169, 0.0063]])

In [185]:
torch.relu(z)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1],
        [1, 1, 1]])

In [189]:
b = a[:]
id(a) == id(b)

False